---
apiVersion: v1
kind: Service
metadata:
  name: my-app-python
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app-python
          image: edulcorada/app-python:1.0
          ports:
            - containerPort: 5000