---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: app-python
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
spec:
  rules:
  - host: host1.domain.ext
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app-python
          image: edulcorada/app-python:1.0
          ports:
            - containerPort: 5000