apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: edulcorada/app-python:1.0
        ports:
        - containerPort: 5000